<section class="section">
    <h1 class="section__header center">About</h1>

    <div class="section__content">
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cum ratione nihil totam omnis repellendus repellat illum fugiat assumenda sed neque similique officia, harum, doloribus iste dolorum doloremque exercitationem suscipit eius alias et cupiditate temporibus! Quis corrupti voluptate ipsam dicta similique doloribus et ullam itaque rem culpa veniam ipsum, suscipit non ratione voluptas nostrum esse. Recusandae quae tenetur ratione ut a reprehenderit quam non sunt quasi, eveniet vel ad nam repellendus deserunt molestias cumque aspernatur. Aliquam at fugiat nesciunt accusamus nostrum velit esse repellendus rerum perferendis, culpa iusto nam praesentium ex error distinctio quisquam neque sint ratione hic numquam voluptatem dignissimos dolores quibusdam. Aspernatur minima, placeat voluptates possimus obcaecati dicta expedita molestias aliquam natus dolores velit libero, saepe sapiente ex neque dolore enim molestiae doloribus sunt aperiam sed reiciendis accusamus nemo sint. Eos aperiam soluta eaque impedit ipsam eum aut ut nesciunt quod ipsa ducimus dicta optio odio, voluptates quam est maxime ullam odit nemo quae corrupti? Dignissimos nobis ea sunt asperiores, excepturi maiores pariatur culpa. Quam quisquam aperiam officiis obcaecati voluptate, dolore perspiciatis suscipit dolorem alias deleniti molestias repellat placeat ipsum expedita earum odio, illo id. Fugiat voluptates sequi accusantium error facere, vitae ratione ut eaque, quam sapiente commodi esse eveniet a, minus deserunt enim perferendis rerum fugit perspiciatis at. Non, numquam iure omnis nulla tenetur corporis illo minima aperiam accusamus iusto aut voluptate fuga neque sapiente corrupti laudantium vero perferendis autem quae? Recusandae beatae, hic dolore dolor veniam iste nihil voluptatem numquam. Placeat quibusdam ab perferendis eveniet laborum quia. Asperiores, laboriosam nulla, commodi velit sit officiis quidem ratione ea nostrum odio sed necessitatibus voluptatum nemo inventore hic libero id? Suscipit laboriosam quis delectus. Sed amet hic nisi impedit totam eveniet dolore reiciendis quasi nihil, ducimus vel quisquam pariatur sunt suscipit cum reprehenderit harum illum nobis culpa, perferendis molestiae! Odit.</p>

        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas suscipit dolores deserunt ipsam. Sint facilis sed repellat ipsum laudantium eum ab ullam, expedita quasi deserunt, odio corporis nam atque inventore exercitationem dolorem doloribus nihil cumque vitae nemo quia, eius necessitatibus soluta? Ex provident nostrum cumque fugit eos est blanditiis necessitatibus similique molestias aut, temporibus consequuntur qui quia autem suscipit dolore. Sit nobis inventore minima eos in nam recusandae necessitatibus impedit dolorem tempora molestiae, vitae consectetur magni corrupti similique qui ratione consequuntur natus ipsam ullam officia velit et? Voluptates voluptas explicabo voluptate est quod? Eius ipsam, sint blanditiis distinctio repudiandae error ipsum hic voluptatem, iusto eos voluptas maiores, itaque quas alias cum facere ex unde. Magni quo ullam aliquam autem officia necessitatibus ut commodi amet, sed doloremque ex quam earum corrupti sapiente libero non nesciunt rem ratione nisi consequuntur repellat? Accusantium rem magni distinctio voluptatibus tempora error dolorem placeat eligendi minima hic cumque corrupti magnam blanditiis quis voluptates possimus, facere facilis laboriosam! Hic voluptates soluta repellendus in? Provident quasi excepturi placeat quo enim aut consequuntur ut reprehenderit nam, animi repellendus voluptatem sapiente fuga ipsa, qui corrupti aliquam? Animi totam molestias sunt deserunt natus minus pariatur maiores exercitationem accusamus quod sapiente omnis rerum modi, possimus dolores illum quos iusto, ipsum eum laborum! Deleniti eligendi perferendis recusandae dicta quasi id iusto, facilis ad tempore nemo beatae, nihil repellat consequatur autem unde, vero sequi neque optio voluptatibus? Atque numquam sequi culpa, laudantium totam eum. Beatae, autem? Quia nemo hic modi ipsam at eius ex, repellat dolores, ipsa debitis omnis fugiat nesciunt blanditiis aliquam ab minima nisi et illo tenetur corrupti laboriosam repudiandae reiciendis incidunt. Laudantium eligendi tenetur, incidunt suscipit quis modi cum in ullam enim laboriosam laborum itaque animi! Dolor impedit assumenda, temporibus eum minus architecto iste repellat, nulla perspiciatis ullam quos. Ullam, ut.</p>

        <div class="section__cta">
            <a href="/" class="btn btn__cta nav-page">Home</a>
        </div>
    </div>
</section>